db:
  url: !ENV ${POSTGRESQL_URL}
  echo_flag: true
  future_flag: true
  # Drop all saved data in database before initialization.
  drop_all_flag: true

web_app:
  host: $ENV {STORAGE_HOST}
  port: $ENV {STORAGE_PORT}
  config_log_path: "config_log.ini"
  reload_flag: True
  workers_num: 4